pipeline {
    agent {
        kubernetes {
        // Define the pod template with container template
        containerTemplate {
            // Define the container template
            containers {
                containerTemplate {
                    name 'gradle'
                    image 'gradle'
                    command 'sleep'
                    args '30d'
                }
            }
            // Label the pod
            label 'POD_LABEL'
        }
    }
}
    stages {
        stage('Clone repo and make gradlew executable') {
            steps {
                git 'https://github.com/bookmil/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
                sh '''
                cd Chapter08/sample1
                chmod +x gradlew
                ./gradlew test
                '''
            }
        }
        stage("Code coverage if master") {
            when { branch 'master' }
            steps {
                sh '''
                pwd
                cd Chapter08/sample1
                ./gradlew jacocoTestCoverageVerification
                '''
            }
        }
    }
}
