pipeline {
    agent {
        kubernetes {
            containerTemplate {
                name 'gradle'
                image 'gradle'
                command 'sleep'
                args '30d'
            }
        }
    }
    stages {
        stage('clone repo and make gradlew executable') {
            steps {
                git url: 'https://github.com/bookmil/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition', branch: 'master'
                sh '''
                    cd Chapter08/sample1
                    chmod +x gradlew
                '''            
            }
        }
        stage('Code cover if master') {
            when { branch 'master'}
            steps {
                sh '''
                    cd Chapter08/sample1
                    ./gradlew test
                    ./gradlew jacocoTestCoverageVerification
                '''
            }
        }
        stage('non master run checkstyle') {
            when { not { branch 'master'}}
            steps {
                sh '''
                    cd Chapter08/sample1
                    ./gradlew checkstyleMain
                '''
            }
        }
    }
    post {
        success {
            echo "tests pass!"
        }

        failure {
            echo "tests fail!"
        }

        always {
            publishHTML (target: [
            reportDir: 'Chapter08/sample1/build/reports/tests/test',
            reportFiles: 'index.html',
            reportName: "JaCoCo Report"
            ])
        }
    }
}

   