pipeline {
     agent any
     environment {
         BUILD_TIMESTAMP = "${new Date().format('yyyyMMddHHmmss')}"
     }
     triggers {
          pollSCM('* * * * *')
     }
     stages {
          stage("Compile") {
               steps {
                   dir('Chapter08/sample1') {
                       sh "chmod +x gradlew"
                       sh "./gradlew compileJava"
                   }
               }
          }
          stage("Unit test") {
               steps {
                   dir('Chapter08/sample1') {
                       sh "./gradlew test"
                   }
               }
          }
          stage("Code coverage") {
               steps {
                   dir('Chapter08/sample1') {
                       sh "./gradlew jacocoTestReport"
                       sh "./gradlew jacocoTestCoverageVerification"
                   }
               }
          }
          stage("Checkstyle Test") {
              steps {
                  dir('Chapter08/sample1') {
                      sh "./gradlew checkstyleTest"
                  }
              }
          }
          stage("Static code analysis") {
               steps {
                   dir('Chapter08/sample1') {
                       sh "./gradlew checkstyleMain"
                   }
               }
          }
          stage("Package") {
               steps {
                   dir('Chapter08/sample1') {
                       sh "./gradlew build"
                   }
               }
          }

          stage("Docker build") {
               steps {
                    sh "docker build -t leszko/calculator:${BUILD_TIMESTAMP} ."
               }
          }

          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials',
                               usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }

          stage("Docker push") {
               steps {
                    sh "docker push leszko/calculator:${BUILD_TIMESTAMP}"
               }
          }

          stage("Update version") {
               steps {
                    sh "sed  -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' calculator.yaml"
               }
          }
          
          stage("Deploy to staging") {
               steps {
                    sh "kubectl config use-context staging"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }

          stage("Acceptance test") {
               steps {
                    sleep 60
                    sh "chmod +x acceptance-test.sh && ./acceptance-test.sh"
               }
          }

          stage("Release") {
               steps {
                    sh "kubectl config use-context production"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }
          stage("Smoke test") {
              steps {
                  sleep 60
                  sh "chmod +x smoke-test.sh && ./smoke-test.sh"
              }
          }
     }
}

post {
    success { 
        publishHTML(target: [
            reportDir: 'Chapter08/sample1/build/reports/checkstyle',
            reportFiles: 'main.xml',
            reportName: 'Jacoco Checkstyle Report'
        ])
    }
}
